#!/usr/bin/env python3
"""M4: the atlas map's pin data → campaign/site/atlas-data.js (window.CaulAtlasData).

The old atlas page (campaign/atlas/index.html) carried an inline DATA object — the map's pins,
legend, focus rectangle and gazetteer. This lifts it out, rewrites each waypoint's link from the
old page path (celsian-athenaeum.html) to its atlas tab route (#atlas/celsian-athenaeum), and
writes it as a data file campaign/site/map.js reads. Nothing else changes; the map image stays at
campaign/atlas/umbra-map.jpeg.

    python3 campaign/source/build_map.py

Proves the output: it parses; every pin/gazetteer link that was an .html page is now an #atlas
route to a migrated atlas doc (or stays null).
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CAMPAIGN = os.path.dirname(HERE)
SRC = os.path.join(CAMPAIGN, "atlas", "index.html")
OUT = os.path.join(CAMPAIGN, "site", "atlas-data.js")
DOCS_ATLAS = os.path.join(CAMPAIGN, "docs", "atlas")


def extract_data():
    s = open(SRC, encoding="utf-8").read()
    i = s.index("const DATA")
    j = s.index("=", i) + 1
    # the object literal from the first { to its matching }
    k = s.index("{", j)
    depth, n = 0, k
    while n < len(s):
        if s[n] == "{":
            depth += 1
        elif s[n] == "}":
            depth -= 1
            if depth == 0:
                break
        n += 1
    return json.loads(s[k:n + 1])


def reroute(url):
    if not url:
        return url
    if url.endswith(".html"):
        return "#atlas/" + os.path.basename(url)[:-5]
    return url


def main():
    data = extract_data()
    for p in data.get("pins", []):
        p["url"] = reroute(p.get("url"))
    for g in data.get("gazetteer", []):
        g["url"] = reroute(g.get("url"))
    body = ("/* campaign/site/atlas-data.js — GENERATED by campaign/source/build_map.py from\n"
            "   campaign/atlas/index.html; do not edit by hand. The atlas map's pins, legend and\n"
            "   gazetteer, each waypoint's link rerouted to its #atlas/<place> tab. */\n"
            "window.CaulAtlasData = " + json.dumps(data, ensure_ascii=False) + ";\n")
    open(OUT, "w", encoding="utf-8").write(body)
    # proof
    reparsed = json.loads(open(OUT, encoding="utf-8").read().split("=", 1)[1].rstrip().rstrip(";"))
    atlas_stems = {f[:-5] for f in os.listdir(DOCS_ATLAS) if f.endswith(".html")}
    bad = 0
    for coll in ("pins", "gazetteer"):
        for e in reparsed.get(coll, []):
            u = e.get("url")
            if u is None:
                continue
            if not u.startswith("#atlas/"):
                bad += 1; print("NOT REROUTED %s: %r" % (e.get("name"), u))
            elif u[len("#atlas/"):] not in atlas_stems:
                bad += 1; print("DANGLING %s: %s (no migrated atlas doc)" % (e.get("name"), u))
    print("build_map: %d pins, %d gazetteer rows → %s; every waypoint link resolves: %s"
          % (len(reparsed.get("pins", [])), len(reparsed.get("gazetteer", [])),
             os.path.relpath(OUT, os.getcwd()), "OK" if not bad else "FAILED (%d)" % bad))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
