#!/usr/bin/env python3
"""M4: the GM's lore/secrets pages (campaign/gm/) → one Behind-the-Veil document,
campaign/docs/veil.html, rendered in the GM Notes pane behind its spoiler gate (VttConfig.notes).

Per the owner's split (2026-09-24): the lore pages (the Behind-the-Veil hub, the GM canon of
persons/places/factions/adversaries, the cosmology, the author's notes, the faeries, the Sylvie
draft, the vignette) go behind the veil; the live-tracking pages (threads, track-npcs, track-items,
planning) become GM-pane pack state instead and are NOT here.

    python3 campaign/source/build_veil.py          # write, then prove
    python3 campaign/source/build_veil.py --check   # prove only

Each page's <div class="wrap"> content region is concatenated in order, each in a <section id="…">;
gm→gm links become in-page anchors (#<stem>), player-section links their site routes (for reference
when the GM opens the site), assets kept under campaign/. Proof: every source page's region text
appears in the veil, in order; exits 1 on a difference.
"""
import html
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CAMPAIGN = os.path.dirname(HERE)
OUT = os.path.join(CAMPAIGN, "docs", "veil.html")
sys.path.insert(0, HERE)
from migrate_docs import region, parse, DIR_ROUTE   # reuse the proven content-region extractor

# lore pages behind the veil, in reading order (the hub first)
LORE = ["index", "cosmology", "canon-persons", "canon-places", "canon-factions", "canon-bestiary",
        "faeries-thistleglass", "sylvie-draft", "vignette", "design-notes"]
CHECK = "--check" in sys.argv


def rewrite(url, stem):
    if re.match(r"^(https?:|mailto:|data:|#)", url):
        return url
    path, _, frag = url.partition("#")
    base = "gm"
    target = os.path.normpath(os.path.join(base, path)) if path else "gm/" + stem + ".html"
    tdir = os.path.dirname(target)
    tstem = os.path.basename(target)[:-5] if target.endswith(".html") else None
    if tdir == "gm" and tstem:                       # gm→gm: an in-page anchor within the veil
        return "#" + tstem
    if tdir == "play":
        return "gm/play.html"
    if not target.endswith(".html"):
        return "campaign/" + target
    route = DIR_ROUTE.get(tdir)
    if route and tstem:
        return "#" + route + ("" if tstem == "index" else "/" + tstem)
    return url


def section(stem):
    body = region("gm/" + stem + ".html")
    body = re.sub(r'\b(href|src)="([^"]*)"',
                  lambda m: '%s="%s"' % (m.group(1), rewrite(html.unescape(m.group(2)), stem).replace("&", "&amp;")),
                  body)
    return '<section id="%s">\n%s</section>\n' % (stem, body)


def main():
    parts = [section(s) for s in LORE]
    doc = ('<div class="wrap">\n'
           '<!-- GENERATED by campaign/source/build_veil.py from campaign/gm/ — do not edit by hand. -->\n'
           + "\n".join(parts) + '</div>\n')
    if not CHECK:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        open(OUT, "w", encoding="utf-8").write(doc)
    # proof: each source region's text appears in the veil, in order
    veil_text = "".join(parse(open(OUT, encoding="utf-8").read()).out)
    bad, pos = 0, 0
    for stem in LORE:
        t = "".join(parse(region("gm/" + stem + ".html")).out).strip()
        k = veil_text.find(t[:200], pos)
        if k < 0:
            bad += 1; print("MISSING or OUT OF ORDER: %s" % stem)
        else:
            pos = k + len(t) - 200
        print("  %-22s %6d chars, present & in order: %s" % (stem, len(t), k >= 0))
    if bad:
        sys.exit("%d problem(s)." % bad)
    print("build_veil: OK — %d lore pages behind the veil, every one present in order." % len(LORE))


if __name__ == "__main__":
    main()
