#!/usr/bin/env python3
"""M4: the old wiki stylesheet, scoped under `.caul-doc` → campaign/site/umbra.css.

The campaign's documents render inside the VTT's pages, whose own stylesheet defines some of the
same things and styles the same elements. Scoping every rule to `.caul-doc` — the element each
campaign document is drawn into — keeps the wiki's look where it was and leaves the VTT's pages
untouched: `:root`, `html` and `body` become `.caul-doc` itself, every other selector a descendant
of it. @media / @supports are scoped inside; @keyframes / @font-face copied as they are. Nothing
but selectors changes. A small hand file (campaign/site/caul-doc.css) then fits the paper to the
frame (undo the old body's `min-height:100vh` and fixed backgrounds).

    python3 campaign/source/scope_css.py

Proves the output: every declaration block of the source appears in it the same number of times,
and every output selector starts with `.caul-doc`.
"""
import os
import re
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
CAMPAIGN = os.path.dirname(HERE)
SRC = os.path.join(CAMPAIGN, "umbra.css")
OUT = os.path.join(CAMPAIGN, "site", "umbra.css")
SCOPE = ".caul-doc"


def strip_comments(css):
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def blocks(css):
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j < 0:
            if css[i:].strip():
                raise SystemExit("stray text: %r" % css[i:][:80])
            break
        depth, k = 1, j + 1
        while depth:
            if css[k] == "{":
                depth += 1
            elif css[k] == "}":
                depth -= 1
            k += 1
        out.append((css[i:j].strip(), css[j + 1:k - 1]))
        i = k
    return out


def scope_selector(sel):
    sel = sel.strip()
    m = re.match(r"^(:root|html|body)\b(.*)$", sel)
    if m:
        return SCOPE + m.group(2)
    return SCOPE + " " + sel


def scope(css, decls):
    out = []
    for pre, body in blocks(css):
        if pre.startswith("@media") or pre.startswith("@supports"):
            out.append(pre + "{\n" + scope(body, decls) + "}")
        elif pre.startswith("@"):
            out.append(pre + "{" + body + "}")
        else:
            decls.append(body.strip())
            out.append(",".join(scope_selector(s) for s in pre.split(",")) + "{" + body + "}")
    return "\n".join(out) + "\n"


def main():
    src_decls = []
    css = strip_comments(open(SRC, encoding="utf-8").read())
    body = scope(css, src_decls)
    head = ("/* campaign/site/umbra.css — GENERATED by campaign/source/scope_css.py from\n"
            "   campaign/umbra.css; do not edit by hand. Every rule is scoped to .caul-doc, the\n"
            "   element a campaign document is drawn into. caul-doc.css fits the paper to the frame. */\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write(head + body)
    # proof
    got_decls, bad = [], 0

    def walk(c):
        nonlocal bad
        for pre, b in blocks(c):
            if pre.startswith("@media") or pre.startswith("@supports"):
                walk(b)
            elif not pre.startswith("@"):
                got_decls.append(b.strip())
                for s in pre.split(","):
                    if not s.strip().startswith(SCOPE):
                        bad += 1
                        print("UNSCOPED: %s" % s.strip())
    walk(strip_comments(open(OUT, encoding="utf-8").read()))
    if Counter(got_decls) != Counter(src_decls):
        bad += 1
        print("DECLARATIONS DIFFER")
    print("scope_css: %d rules → %s; every declaration kept, every selector under %s: %s"
          % (len(got_decls), os.path.relpath(OUT, os.getcwd()), SCOPE, "OK" if not bad else "FAILED (%d)" % bad))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
